[workspace]
members = ["wire", "core", "core-ffi", "core-wasm", "server", "cli"]
resolver = "3"

[workspace.package]
version = "0.0.0"
edition = "2024"
rust-version = "1.92.0"
license = "MIT"
publish = false

[workspace.dependencies]
babytrack-wire = { path = "wire" }
babytrack-core = { path = "core" }
