// English launch copy lives in one catalog so routes can be translated later.
export const copy = {
  app: 'Lantern', preview: 'Early web preview', today: 'Today', history: 'History',
  family: 'Family', createFamily: 'Create a Family', noAccount: 'Start tracking here without an account.',
  addChild: 'Add a child', childName: 'Child name', birthDate: 'Birthday',
  growthSex: 'Sex for growth charts', unspecified: 'Unspecified', female: 'Female', male: 'Male',
  save: 'Save', cancel: 'Cancel', localOnly: 'On this browser',
  localDescription: 'This Family is saved in this browser profile. Create a shared Family on Android, then invite this browser to join it.',
  chooseChild: 'Choose a child', recent: 'Recent entries', emptyHistory: 'No entries yet.',
  addActivity: 'Add activity', diaper: 'Diaper', bottle: 'Bottle', note: 'Note',
  wet: 'Wet', dirty: 'Dirty', both: 'Both', dry: 'Dry',
  amount: 'Amount (mL)', content: 'Contents', formula: 'Formula', milk: 'Breast milk', mixed: 'Mixed', otherMilk: 'Other',
  noteText: 'Note', allEntries: 'All entries', todaySummary: 'Today at a glance',
  feeds: 'Feeds', diapers: 'Diapers', children: 'Children',
  localNotice: 'Local preview · this browser only', sharedNotice: 'Encrypted Family · synced through relay', birthUnknown: 'Age unknown',
  loading: 'Loading…', welcomeTitle: 'A calmer place to keep the little details.',
  welcomeDetail: 'A new Family stays in this browser profile. Use an invitation below to join an existing shared Family.',
  addChildPrompt: 'Add a child to start tracking.', type: 'Type',
  switchFamily: 'Switch Family',
  back: 'Back', breastFeed: 'Breastfeed', leftBreast: 'Left breast', rightBreast: 'Right breast',
  feedingNow: 'Feeding now', feedingPaused: 'Paused', tapSideToStart: 'Tap a side to start.',
  tapToStart: 'Start or resume', tapToPause: 'Tap to pause',
  breastTimerHint: 'Tap the active side to pause, or the other side to switch. Paused time is excluded.',
  completedSides: 'Completed sides', saveBreast: 'Save feeding', discardSession: 'Discard session',
  discardBreastConfirm: 'Discard this unsaved feeding session?',
  timerTooShort: 'Keep a side running for at least one second before pausing or saving.',
  timerTooLong: 'Feeding time cannot exceed four hours.',
  timerTooManySegments: 'A feeding can have up to eight sides. Save this session to finish.',
  timerEmpty: 'Start a side before saving.',
  invalidDuration: 'Use minutes:seconds, such as 5:30.',
  futureEnd: 'The edited feeding cannot end in the future.',
  edit: 'Edit', editBreast: 'Edit breast feed',
  editBreastHint: 'Change each side and its active time. Pause before a side is excluded from feeding totals. The original start time stays fixed.',
  side: 'Side', pauseBefore: 'Pause before (minutes:seconds)',
  durationMmSs: 'Feeding time (minutes:seconds)', removeSide: 'Remove side', addSide: 'Add side',
  saveChanges: 'Save changes',
  joinFamily: 'Join a Family', invitationLink: 'Invitation link', join: 'Join',
  confirmJoin: 'Invitation ready to join', joinThisFamily: 'Join this Family',
  dismissInvitation: 'Dismiss invitation',
  joinHistoryWarning: 'Joining gives this browser access to the Family history already shared with members. This browser profile receives its own device grant.',
  invitationHint: 'Open or paste a link from a Family manager. This browser profile becomes a separate device.',
  waitingInvite: 'Checking the invitation', waitingChallenge: 'Claim sent · waiting for the manager device',
  waitingGrant: 'Proof sent · waiting for the Family key grant',
  loadingHistory: 'Loading verified Family history before this device is ready',
  loadingControls: 'Checking the latest Family sharing changes',
  waitingClaimResult: 'Claim result is uncertain · retrying signed checks',
  inviteClaimed: 'This invitation was already used. Ask a manager for a new link.',
  inviteCanceled: 'This invitation was canceled. Ask a manager for a new link.',
  inviteExpired: 'This invitation expired. Ask a manager for a new link.',
  inviteInvalidated: 'The inviting device lost manager access. Ask a manager for a new link.',
  joining: 'Checking encrypted Family access…', joinPending: 'Joining a Family',
  shared: 'Shared Family', sharedDescription: 'This browser has its own device grant. Entries are encrypted before relay upload.',
  syncNow: 'Sync now', syncReady: 'Up to date', syncMore: 'Loading more Family history', syncFailed: 'Saved here · waiting for a connection',
  savedPending: 'Saved here · waiting to sync',
  removedTitle: 'This device no longer has shared access',
  removedDetail: 'Locally held history stays here. Pending saved work is copied into an independent Family. The old Family is an archive on this browser.',
  removedArchive: 'Access ended · local archive available',
  removedCopied: 'Access ended · private copy saved on this browser',
  redirectedCopy: 'This action was saved in your independent local Family because shared access ended.',
  makePrivateCopy: 'Make an independent copy', openPrivateCopy: 'Open private copy',
  backup: 'Backup and restore',
  backupDescription: 'Export the locally held current state as a readable file. Restoring creates a new local Family with a fresh identity.',
  backupPoint: (cursor) => `Saved public history through entry ${new Intl.NumberFormat().format(cursor)}.`,
  backupIncomplete: 'The file marks a known history gap; sync may fill it before export.',
  backupComplete: 'The last sync reached the end of the visible log.',
  exportBackup: 'Export readable backup', restoreBackup: 'Restore file into a new Family',
  restoreDescription: 'Lost this browser’s saved data? A readable backup restores its saved records into a new local Family.',
  restoreFile: 'Choose a backup file',
  pendingJoinResume: 'Resume joining',
  // Activities, choices, and units shared with Android.
  groupFeeding: 'Feeding', groupSleepDiapers: 'Sleep and diapers', groupHealth: 'Health', groupNotes: 'Notes',
  pumping: 'Pumping', pump: 'Pump', solids: 'Solids', growth: 'Growth', temperature: 'Temperature',
  medication: 'Medication', breast: 'Breast', left: 'Left', right: 'Right',
  placeCrib: 'Crib', placePram: 'Pram', placeContact: 'Contact', placeCar: 'Car', placeOther: 'Other place',
  placeNone: 'Not recorded', sleepPlace: 'Where did the sleep happen?', place: (value) => `Place: ${value}`,
  filterAll: 'All', filterCare: 'Growth & care', filterNotes: 'Notes',
  newerEntry: 'Entry from a newer app version',
  entry: (...parts) => parts.filter((part) => part != null && part !== '').join(' · '),
  totalMl: (ml) => `${ml} mL total`, leftMl: (ml) => `L ${ml} mL`, rightMl: (ml) => `R ${ml} mL`,
  head: (value) => `head ${value}`,
  minutesShort: (count) => `${new Intl.NumberFormat().format(count)} min`,
  hoursShort: (count) => `${new Intl.NumberFormat().format(count)} h`,
  hoursMinutesShort: (hours, mins) => `${new Intl.NumberFormat().format(hours)} h ${new Intl.NumberFormat().format(mins)} min`,
  justNow: 'Just now', minutesAgo: (count) => `${new Intl.NumberFormat().format(count)} min ago`,
  hoursAgo: (count) => `${new Intl.NumberFormat().format(count)} h ago`,
  hoursMinutesAgo: (hours, mins) => `${new Intl.NumberFormat().format(hours)} h ${new Intl.NumberFormat().format(mins)} min ago`,
  daysAgo: (count) => counted(count, 'day ago', 'days ago'),
  yesterday: 'Yesterday', yesterdayAt: (time) => `Yesterday, ${time}`, dateAt: (date, time) => `${date}, ${time}`,
  forChild: (name) => `For ${name}`, now: 'Now', changeTime: 'Change time', useNow: 'Use now',
  whenLabel: 'When', futureTime: 'Choose a time that has already passed.',
  saveFailed: 'Could not complete the action. Try again.',
  inBottle: 'In the bottle', unit: 'Unit', bottleAmount: 'Bottle amount', less: 'Less', more: 'More',
  sameAsLast: (amount, unit) => `Same as last: ${amount} ${unit}`, saveBottle: 'Save bottle',
  saveDiaper: 'Save diaper', timerMode: 'Timer', minutesMode: 'Enter minutes', sideLabel: 'Side',
  minutesOnSide: 'Minutes on selected side', addSegment: 'Add segment', removeSegment: 'Remove last segment',
  segmentsDraft: (value) => `Segments: ${value}`, saveBreastFeed: 'Save breast feed',
  startPumpTimer: 'Start pumping timer', stopTimer: 'Stop timer', minutesPumping: 'Minutes pumping',
  amount: 'Amount', leftMlLabel: 'Left (mL)', rightMlLabel: 'Right (mL)', totalMlLabel: 'Total (mL), instead of sides',
  savePumping: 'Save pumping', pumpRule: 'Enter left and right amounts, or one total.',
  foods: 'Foods (one per line)', amountEaten: 'Amount eaten (optional)', saveSolids: 'Save solids',
  minutesSlept: 'Minutes slept', saveSleep: 'Save sleep', addPastSleep: 'Add past sleep',
  weight: 'Weight', length: 'Length', headCircumference: 'Head circumference', saveGrowth: 'Save growth',
  growthRule: 'Enter at least one measurement.', temperatureIn: (unit) => `Temperature (${unit})`,
  saveTemperature: 'Save temperature', medicationName: 'Medication name', doseAmount: 'Dose amount',
  doseUnit: 'Dose unit', saveMedication: 'Save medication', whatHappened: 'What happened?', saveNote: 'Save note',
  breastInProgress: 'Breast feed in progress', breastPaused: 'Breast feed paused',
  leftRight: (left, right) => `Left ${left} · Right ${right}`, openTimer: 'Open timer',
  breastFeedButton: 'Breast feed', noFeeds: 'No feeds logged yet', sleeping: 'Sleeping',
  since: (time) => `Since ${time}`, slept: (duration, time) => `Slept ${duration} · woke ${time}`,
  noSleep: 'No sleep logged yet', wetNow: 'Wet now', wetNowLabel: 'Log a wet diaper now',
  logDiaper: 'Log diaper', noDiapers: 'No diapers logged yet', soFarToday: 'So far today',
  nothingToday: 'Nothing logged today yet.',
  feedLine: (count, ml) => `${counted(count, 'feed', 'feeds')} · bottle ${new Intl.NumberFormat().format(ml)} mL`,
  sleepLine: (duration) => `${duration} of sleep`,
  diaperLine: (count, wet, dirty) => `${counted(count, 'diaper', 'diapers')} · wet ${wet} · dirty ${dirty}`,
  viewTimeline: 'View timeline', dayMode: 'Day', allDays: 'All days', chooseDay: 'Choose day',
  filterLabel: 'Filter entries', feedUnit: (count) => (new Intl.PluralRules().select(count) === 'one' ? 'feed' : 'feeds'),
  bottleMlDetail: (ml) => `${new Intl.NumberFormat().format(ml)} mL bottle`, sleepUnit: 'sleep',
  diaperUnit: (count) => (new Intl.PluralRules().select(count) === 'one' ? 'diaper' : 'diapers'),
  wetDirty: (wet, dirty) => `${wet} wet · ${dirty} dirty`, emptyView: 'No entries in this view.',
  wrongPassword: 'Wrong password or damaged backup file.', backupSaved: 'Backup saved',
  csvSaved: 'Analysis CSV saved', backupTooLarge: 'This backup is too large to restore here.',
  backupDamaged: 'This backup file is damaged or unsupported.',
  lastFileSave: (time) => `Last completed file save: ${time}`,
  changesSinceSave: 'Changes since that save are not in that file.',
  protectedDescription: 'A protected backup is encrypted with your password. Without the password it cannot be restored.',
  protectWithPassword: 'Protect with password', backupPassword: 'Backup password', saveBackup: 'Save backup',
  exportCsv: 'Export analysis CSV', enterBackupPassword: 'Enter the backup password to restore this file.',
  protectedPassword: 'Password for protected backup', checkProtected: 'Check protected backup',
  filePreview: (time, count) => `File saved at ${time} · ${new Intl.NumberFormat().format(count)} records`,
  fileKnownGap: 'This file reports a known gap in shared history.', restoreAsNew: 'Restore as new Family',
  working: 'Working…', dataAndBackups: 'Data and backups',
  devicesWithAccess: (count) => `${counted(count, 'device has', 'devices have')} access`,
  familyAccess: 'Family access', hideFamilyAccess: 'Hide Family access', verifiedDevices: 'Devices with verified access',
  thisDevice: 'This device', otherDevice: 'Other device', manager: 'Manager', member: 'Member',
  deviceId: (id) => `ID ${id}`, deviceName: 'Device name', nameDevice: 'Name device',
  managerActionsAndroid: 'Inviting, removing, and changing roles are done from an Android manager device for now.',
  makeFamilyCopy: 'Make a private Family copy', privateCopyReady: 'Private copy ready. It is a separate Family on this browser.',
  moveSession: 'Move session', editTime: 'Edit time', editSleepDuration: 'Edit sleep duration',
  editSleepPlace: 'Edit sleep place', editBottle: 'Edit bottle', editDiaperType: 'Edit diaper type',
  editSolids: 'Edit solids', editPumpAmounts: 'Edit pumping amounts', editMedication: 'Edit medication entry',
  editGrowth: 'Edit growth', editTemperature: 'Edit temperature', editNote: 'Edit note',
  addNote: 'Add note to entry', deleteEntry: 'Delete entry', noteDetail: (note) => `Note: ${note}`,
  clearNoteHint: 'Clear the text and save to remove this note.', moveStart: 'New start',
  moveHint: 'The session keeps its duration.', sleepMinutesRule: 'Enter 1 to 1440 minutes that end before now.',
  amountRule: 'Enter a valid amount.', breastStart: 'Start', whenChangingMinutes: 'When changing minutes',
  keepFinish: 'Keep finish time', keepStart: 'Keep start time',
  pumpEditHint: 'Enter separate left/right amounts or one total. Clear the other fields when switching.',
  growthEditHint: 'Leave a measurement blank to keep its saved value. Delete the entry to remove it.',
  deleteConfirm: 'Remove this entry from the Family timeline? Shared devices receive the change when they sync.',
  entryDeleted: 'Entry deleted', undo: 'Undo',
  moreActivities: 'More', select: 'Select', editChildNamed: (name) => `Edit ${name}`,
  clearBirthDate: 'Clear birth date', editChild: 'Edit child profile', addAnotherChild: 'Add another child',
  childOptions: 'Child options', addActivityTitle: 'Add activity',
  lastSide: 'Last side', lastFeedEnded: (side) => `Last feed ended on ${side}`, finishedAt: 'Finished',
  sleep: 'Sleep', startSleep: 'Start sleep timer', stopSleep: 'Stop sleep', sleepRunning: 'Sleep · running',
  sleepingSince: (time) => `Sleeping since ${time}`,
  feedCount: (count) => counted(count, 'feed', 'feeds'),
  diaperCount: (count) => counted(count, 'diaper', 'diapers'),
  sideNumber: (number) => `Side ${new Intl.NumberFormat().format(number)}`,
  familyNumber: (number) => `Family ${new Intl.NumberFormat().format(number)}`,
  ageUnit: {
    day: { one: 'day', other: 'days' }, week: { one: 'week', other: 'weeks' },
    month: { one: 'month', other: 'months' }, year: { one: 'year', other: 'years' },
  },
};

function counted(count, one, other) {
  const form = new Intl.PluralRules().select(count) === 'one' ? one : other;
  return `${new Intl.NumberFormat().format(count)} ${form}`;
}

export function ageLabel(birthDay) {
  if (birthDay == null) return copy.birthUnknown;
  const today = new Date();
  const birth = new Date(Number(birthDay) * 86400000);
  const days = Math.max(0, Math.floor((Date.UTC(today.getFullYear(), today.getMonth(), today.getDate()) - birth.getTime()) / 86400000));
  let months = (today.getFullYear() - birth.getUTCFullYear()) * 12 + today.getMonth() - birth.getUTCMonth();
  if (today.getDate() < birth.getUTCDate()) months -= 1;
  months = Math.max(0, months);
  const unit = days < 14 ? 'day' : months < 1 ? 'week' : months < 24 ? 'month' : 'year';
  const count = unit === 'day' ? days : unit === 'week' ? Math.floor(days / 7) :
    unit === 'month' ? months : Math.floor(months / 12);
  const form = new Intl.PluralRules().select(count);
  return `${new Intl.NumberFormat().format(count)} ${copy.ageUnit[unit][form] ?? copy.ageUnit[unit].other}`;
}
