#!/usr/bin/env python3
"""Exercise one local caregiver flow through the installed Android UI."""

from __future__ import annotations

import argparse
import re
import time

from android_ui import (
    APK, PACKAGE, adb, dismiss_keyboard, find, nodes, open_capture,
    open_entry_actions, open_family, open_history,
    scroll_up, serial, stage, tap, tap_tab, run_scenario,
)


def main(quick: bool = False) -> None:
    target = serial()
    if adb(target, "shell", "getprop", "ro.kernel.qemu").strip() != "1":
        raise RuntimeError("This destructive smoke check runs only on an emulator")
    if not APK.exists():
        raise RuntimeError(f"Build the debug APK first: {APK}")
    adb(target, "install", "-r", str(APK))
    adb(target, "shell", "pm", "clear", PACKAGE)
    adb(target, "shell", "am", "start", "-n", f"{PACKAGE}/.MainActivity")
    find(target, "Join a Family")
    tap(target, "Privacy", scroll=True)
    find(target, "Privacy")
    tap(target, "Got it")
    tap(target, "Add your child")
    tap(target, "Name or nickname", scroll=True)
    adb(target, "shell", "input", "text", "UITestChild")
    dismiss_keyboard(target)
    # Leaving setup preserves the draft but must not create an empty Family.
    adb(target, "shell", "input", "keyevent", "4")
    find(target, "Add your child")
    tap(target, "Add your child")
    find(target, "UITestChild")
    adb(target, "shell", "am", "force-stop", PACKAGE)
    adb(target, "shell", "am", "start", "-n", f"{PACKAGE}/.MainActivity")
    find(target, "UITestChild")
    tap(target, "Name or nickname", scroll=True)
    # Let the IME finish opening so the tap exercises the visible save footer.
    time.sleep(1)
    tap(target, "Start tracking", scroll=True, actionable=True)
    find(target, "Feeding")
    find(target, "UITestChild")
    tap(target, "Family", actionable=True)
    tap(target, "Family options", scroll=True)
    find(target, "Sharing controls", scroll=True)
    tap(target, "Hide Family options", scroll=True)
    tap(target, "Child options", scroll=True)
    find(target, "Edit child profile", scroll=True)
    find(target, "Add another child", scroll=True)
    tap(target, "Hide child options", scroll=True)
    tap(target, "Today", actionable=True)
    tap(target, "View timeline", scroll=True)
    find(target, "No entries yet.")
    tap(target, "Today", actionable=True)
    tap(target, "Bottle", scroll=True)
    find(target, "Bottle amount", scroll=True)
    adb(target, "shell", "input", "keyevent", "4")
    open_capture(target, "Sleep")
    find(target, "Minutes slept", scroll=True)
    adb(target, "shell", "input", "keyevent", "4")
    tap(target, "Wet now", scroll=True)
    tap(target, "History", actionable=True)
    find(target, "Diaper · Wet", scroll=True)
    open_entry_actions(target, "Diaper · Wet")
    tap(target, "Edit diaper type", scroll=True)
    tap(target, "Dirty")
    tap(target, "Save changes")
    find(target, "Diaper · Dirty", scroll=True)
    scroll_up(target, 2)
    tap(target, "Feeds", scroll=True)
    find(target, "No entries in this view.", scroll=True)
    scroll_up(target, 2)
    tap(target, "All", scroll=True)
    find(target, "Diaper · Dirty", scroll=True)
    adb(target, "shell", "am", "force-stop", PACKAGE)
    adb(target, "shell", "am", "start", "-n", f"{PACKAGE}/.MainActivity")
    find(target, "UITestChild")
    tap(target, "History", actionable=True)
    find(target, "Diaper · Dirty", scroll=True)
    open_entry_actions(target, "Diaper · Dirty")
    tap(target, "Delete entry", scroll=True)
    find(target, "Remove this entry from the Family timeline? Shared devices receive the change when they sync.")
    tap(target, "Delete")
    find(target, "No entries yet.", scroll=True)
    adb(target, "shell", "am", "force-stop", PACKAGE)
    adb(target, "shell", "am", "start", "-n", f"{PACKAGE}/.MainActivity")
    find(target, "UITestChild")
    tap(target, "History", actionable=True)
    find(target, "No entries yet.", scroll=True)
    if quick:
        print("Android UI quick Family, diaper, edit, delete, and restart: OK")
        return
    open_capture(target, "Note")
    tap(target, "What happened?", scroll=True)
    adb(target, "shell", "input", "text", "Before")
    dismiss_keyboard(target)
    tap(target, "Save note", scroll=True)
    open_history(target)
    find(target, "Note · Before", scroll=True)
    open_entry_actions(target, "Note · Before")
    tap(target, "Edit note", scroll=True)
    tap(target, "Before")
    adb(target, "shell", "input", "text", "After")
    dismiss_keyboard(target)
    tap(target, "Save changes")
    find(target, "Note · BeforeAfter", scroll=True)
    adb(target, "shell", "am", "force-stop", PACKAGE)
    adb(target, "shell", "am", "start", "-n", f"{PACKAGE}/.MainActivity")
    open_history(target)
    find(target, "Note · BeforeAfter", scroll=True)
    open_capture(target, "Diaper")
    tap(target, "Dry", scroll=True)
    tap(target, "Save diaper", scroll=True)
    open_history(target)
    find(target, "Diaper · Dry", scroll=True)
    open_capture(target, "Bottle")
    tap(target, "Breast milk", scroll=True)
    tap(target, "Bottle amount", scroll=True)
    adb(target, "shell", "input", "text", "90")
    dismiss_keyboard(target)
    tap(target, "Save bottle", scroll=True, actionable=True)
    open_history(target)
    find(target, "Bottle · 90 mL · Breast milk", scroll=True)
    open_entry_actions(target, "Bottle · 90 mL · Breast milk")
    tap(target, "Edit bottle", scroll=True)
    tap(target, "Formula")
    tap(target, "Bottle amount")
    adb(target, "shell", "input", "keyevent", "123")
    adb(target, "shell", "input", "keyevent", "67")
    adb(target, "shell", "input", "keyevent", "67")
    adb(target, "shell", "input", "text", "120")
    dismiss_keyboard(target)
    tap(target, "Save changes")
    find(target, "Bottle · 120 mL · Formula", scroll=True)
    adb(target, "shell", "am", "force-stop", PACKAGE)
    adb(target, "shell", "am", "start", "-n", f"{PACKAGE}/.MainActivity")
    open_capture(target, "Breast feed")
    tap(target, "Enter minutes", scroll=True)
    tap(target, "Minutes on selected side", scroll=True)
    adb(target, "shell", "input", "text", "5")
    dismiss_keyboard(target)
    tap(target, "Add segment", scroll=True)
    scroll_up(target, 12)
    tap(target, "Right", scroll=True)
    tap(target, "Minutes on selected side", scroll=True)
    adb(target, "shell", "input", "text", "8")
    dismiss_keyboard(target)
    tap(target, "Save breast feed", scroll=True)
    open_history(target)
    find(target, "Breast · Left 5 min → Right 8 min", scroll=True)
    open_entry_actions(target, "Breast · Left 5 min → Right 8 min")
    tap(target, "Edit breast feed", scroll=True)
    tap(target, "Right")
    tap(target, "Save changes")
    find(target, "Breast · Right 5 min → Right 8 min", scroll=True)
    adb(target, "shell", "am", "force-stop", PACKAGE)
    adb(target, "shell", "am", "start", "-n", f"{PACKAGE}/.MainActivity")
    open_history(target)
    find(target, "Breast · Right 5 min → Right 8 min", scroll=True)
    scroll_up(target)
    find(target, "Bottle · 120 mL · Formula", scroll=True)
    open_entry_actions(target, "Bottle · 120 mL · Formula")
    tap(target, "Edit bottle", scroll=True)
    tap(target, "US fl oz")
    tap(target, "Bottle amount")
    adb(target, "shell", "input", "text", "4.5")
    dismiss_keyboard(target)
    tap(target, "Save changes")
    find(target, "Bottle · 4.5 US fl oz · Formula", scroll=True)
    dismiss_keyboard(target)
    tap(target, "Edit bottle", scroll=True, actionable=True)
    tap(target, "UK fl oz")
    tap(target, "Bottle amount")
    adb(target, "shell", "input", "text", "4.5")
    dismiss_keyboard(target)
    tap(target, "Save changes")
    find(target, "Bottle · 4.5 UK fl oz · Formula", scroll=True)
    adb(target, "shell", "am", "force-stop", PACKAGE)
    adb(target, "shell", "am", "start", "-n", f"{PACKAGE}/.MainActivity")
    open_history(target)
    find(target, "Bottle · 4.5 UK fl oz · Formula", scroll=True)
    adb(target, "shell", "am", "force-stop", PACKAGE)
    adb(target, "shell", "am", "start", "-n", f"{PACKAGE}/.MainActivity")
    open_family(target)
    tap(target, "Child options", scroll=True)
    tap(target, "Edit child profile", scroll=True)
    tap(target, "Child’s name", scroll=True)
    adb(target, "shell", "input", "keyevent", "123")
    adb(target, "shell", "input", "keyevent", *(["67"] * 30))
    adb(target, "shell", "input", "text", "Renamed")
    dismiss_keyboard(target)
    find(target, "Renamed", contains=True)
    tap(target, "Save changes", scroll=True)
    scroll_up(target, 12)
    find(target, "Renamed", scroll=True, contains=True)
    adb(target, "shell", "am", "force-stop", PACKAGE)
    adb(target, "shell", "am", "start", "-n", f"{PACKAGE}/.MainActivity")
    find(target, "Renamed", scroll=True, contains=True)
    open_capture(target, "Growth")
    tap(target, "Weight", scroll=True)
    adb(target, "shell", "input", "text", "4.2")
    dismiss_keyboard(target)
    tap(target, "Length", scroll=True)
    adb(target, "shell", "input", "text", "54")
    dismiss_keyboard(target)
    tap(target, "Head circumference", scroll=True)
    adb(target, "shell", "input", "text", "35")
    dismiss_keyboard(target)
    tap(target, "Save growth", scroll=True)
    open_history(target)
    find(target, "Growth · 4.2 kg · 54 cm · head 35 cm", scroll=True)
    open_entry_actions(target, "Growth · 4.2 kg · 54 cm · head 35 cm")
    tap(target, "Edit growth", scroll=True)
    tap(target, "4.2", scroll=True)
    adb(target, "shell", "input", "keyevent", "123")
    for _ in range(3):
        adb(target, "shell", "input", "keyevent", "67")
    adb(target, "shell", "input", "text", "4.3")
    dismiss_keyboard(target)
    tap(target, "Save changes", scroll=True)
    find(target, "Growth · 4.3 kg · 54 cm · head 35 cm", scroll=True)
    tap(target, "Edit growth", scroll=True)
    tap(target, "Head circumference", scroll=True, actionable=True)
    adb(target, "shell", "input", "keyevent", "123")
    for _ in range(2):
        adb(target, "shell", "input", "keyevent", "67")
    adb(target, "shell", "input", "text", "35.5")
    dismiss_keyboard(target)
    tap(target, "Save changes", scroll=True)
    find(target, "Growth · 4.3 kg · 54 cm · head 35.5 cm", scroll=True)
    tap(target, "Add note to entry", scroll=True)
    tap(target, "What happened?")
    adb(target, "shell", "input", "text", "GrowthNote")
    dismiss_keyboard(target)
    tap(target, "Save changes")
    find(target, "Note: GrowthNote", scroll=True)
    adb(target, "shell", "am", "force-stop", PACKAGE)
    adb(target, "shell", "am", "start", "-n", f"{PACKAGE}/.MainActivity")
    open_history(target)
    find(target, "Growth · 4.3 kg · 54 cm · head 35.5 cm", scroll=True)
    find(target, "Note: GrowthNote", scroll=True)
    open_capture(target, "Sleep")
    tap(target, "Minutes slept", scroll=True)
    adb(target, "shell", "input", "text", "30")
    dismiss_keyboard(target)
    tap(target, "Crib", scroll=True)
    tap(target, "Save sleep", scroll=True)
    open_history(target)
    find(target, "Sleep · 30 min", scroll=True)
    find(target, "Place: Crib", scroll=True)
    open_entry_actions(target, "Sleep · 30 min")
    tap(target, "Edit sleep duration", scroll=True)
    tap(target, "30")
    adb(target, "shell", "input", "keyevent", "123")
    for _ in range(2):
        adb(target, "shell", "input", "keyevent", "67")
    adb(target, "shell", "input", "text", "20")
    dismiss_keyboard(target)
    tap(target, "Save changes")
    find(target, "Sleep · 20 min", scroll=True)
    find(target, "Place: Crib", scroll=True)
    tap(target, "Edit sleep place", scroll=True)
    tap(target, "Pram")
    tap(target, "Save changes")
    find(target, "Place: Pram", scroll=True)
    adb(target, "shell", "am", "force-stop", PACKAGE)
    adb(target, "shell", "am", "start", "-n", f"{PACKAGE}/.MainActivity")
    open_history(target)
    find(target, "Sleep · 20 min", scroll=True)
    find(target, "Place: Pram", scroll=True)
    open_capture(target, "Temperature")
    tap(target, "Temperature (°C)", scroll=True)
    adb(target, "shell", "input", "text", "37.5")
    dismiss_keyboard(target)
    tap(target, "Save temperature", scroll=True)
    open_history(target)
    find(target, "Temperature · 37.5 °C", scroll=True)
    open_entry_actions(target, "Temperature · 37.5 °C")
    tap(target, "Edit temperature", scroll=True)
    tap(target, "37.5")
    adb(target, "shell", "input", "keyevent", "123")
    for _ in range(4):
        adb(target, "shell", "input", "keyevent", "67")
    adb(target, "shell", "input", "text", "37.8")
    dismiss_keyboard(target)
    tap(target, "Save changes")
    scroll_up(target, 10)
    find(target, "Temperature · 37.8 °C", scroll=True)
    adb(target, "shell", "am", "force-stop", PACKAGE)
    adb(target, "shell", "am", "start", "-n", f"{PACKAGE}/.MainActivity")
    open_history(target)
    find(target, "Temperature · 37.8 °C", scroll=True)
    open_entry_actions(target, "Temperature · 37.8 °C")
    dismiss_keyboard(target)
    tap(target, "Edit temperature", scroll=True, actionable=True)
    tap(target, "°F")
    tap(target, "Temperature (°F)")
    adb(target, "shell", "input", "text", "99")
    dismiss_keyboard(target)
    tap(target, "Save changes")
    find(target, "Temperature · 99 °F", scroll=True)
    adb(target, "shell", "am", "force-stop", PACKAGE)
    adb(target, "shell", "am", "start", "-n", f"{PACKAGE}/.MainActivity")
    open_history(target)
    find(target, "Temperature · 99 °F", scroll=True)
    open_family(target)
    tap(target, "Family options", scroll=True)
    tap(target, "New Family", scroll=True)
    tap(target, "Add child", scroll=True)
    tap(target, "Child’s name", scroll=True)
    adb(target, "shell", "input", "text", "FirstChild")
    dismiss_keyboard(target)
    tap(target, "Add child", scroll=True)
    open_family(target)
    tap(target, "Child options", scroll=True)
    tap(target, "Add another child", scroll=True)
    tap(target, "Child’s name", scroll=True)
    adb(target, "shell", "input", "text", "SelectedChild")
    dismiss_keyboard(target)
    tap(target, "Add child", scroll=True)
    open_capture(target, "Note")
    tap(target, "What happened?", scroll=True)
    adb(target, "shell", "input", "text", "SelectedChildMarker")
    dismiss_keyboard(target)
    tap(target, "Save note", scroll=True)
    open_history(target)
    find(target, "Note · SelectedChildMarker", scroll=True)
    adb(target, "shell", "am", "force-stop", PACKAGE)
    adb(target, "shell", "am", "start", "-n", f"{PACKAGE}/.MainActivity")
    open_history(target)
    find(target, "Note · SelectedChildMarker", scroll=True)
    stage("Live nursing timer across a force-stop")
    open_capture(target, "Breast feed")
    tap(target, "Timer", scroll=True)
    tap(target, "Left", scroll=True, actionable=True)
    time.sleep(2)
    adb(target, "shell", "am", "force-stop", PACKAGE)
    adb(target, "shell", "am", "start", "-n", f"{PACKAGE}/.MainActivity")
    find(target, "Breast feed in progress", scroll=True)
    tap(target, "Open timer", scroll=True)
    tap(target, "Right", scroll=True, actionable=True)
    time.sleep(2)
    tap(target, "Save breast feed", actionable=True)
    open_history(target)
    find(target, "Breast · Left 1 min → Right 1 min", scroll=True)
    open_entry_actions(target, "Breast · Left 1 min → Right 1 min")
    find(target, "Edit breast feed", scroll=True)
    print("Android UI Family/child selection, timeline, logging, edits, and restart: OK")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--quick", action="store_true", help="Run the short push/PR UI path")
    args = parser.parse_args()
    run_scenario("caregiver-quick" if args.quick else "caregiver-full", lambda: main(args.quick))
